config/routes.rb
Rails.application.routes.draw do
  
  root 'clients#index'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions  

  resources :clients do
    resources :projects do
      resources :tasks do
        resources :entries
      end
    end
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :projects
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	has_many :entries
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :entries

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  protected

  def not_authenticated
    redirect_to login_url, :alert => "Login to view this page."
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	before_action :load_client, only: [:show, :edit, :update, :destroy]

	def index
		@clients = Client.all
	end
	
	def new
		@client = Client.new
	end

	def create
		@client = Client.new(client_params)
		if @client.save
			redirect_to root_url :notice => "Client successfully added"
		else 
			render :new
		end
	end

	def update
		if @client.update(client_params)
			redirect_to @client
		else
			render :edit
		end
	end

	def destroy    
    @client.destroy
    redirect_to :clients
  end

  protected

  def client_params
  	params.require(:client).permit(:name)
  end

  def load_client
  	@client = Client.find(params[:id])
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
 

 	before_action :load_client
	before_action :load_project, only: [:show, :edit, :update, :destroy]

	def index
		@projects = Project.all
	end

	def show
		# @project = Project.find(project_params)
	end

	def new
		@project = @client.projects.build
	end

	def create
		@project = @client.projects.build(project_params)
		if @project.save
			redirect_to @client
		else 
			render :new
		end
	end

	def destroy
    @project.destroy
    redirect_to client_path(@client)
  end

  protected

  def project_params
  	params.require(:project).permit(:name)
  end

  def load_project
  	@project = @client.projects.find([:id])
  end

  def load_client
    @client = Client.find(params[:client_id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_action :require_login

	def new
	end

	def create
		user = login(params[:email], params[:password])
		if user
			redirect_back_or_to root_url :notice => "Login successful"
		else
			flash.now.alert = "Login credentials invalid."
		end
	end

	def destroy
		logout
		redirect_to root_url, :notice => "Logged out!"
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	before_filter :load_client
	before_filter :load_project
	before_filter :load_task, only: [:show, :edit, :update, :destroy]


	def index
		@tasks = Task.all
	end

	def show
		# @task = Task.find(params[:id])
	end

	def new
		@task = @project.tasks.build
	end

	def create
		@task = @project.tasks.build(task_params)
		if @task.save
			redirect_to @project
		else 
			render :new
		end
	end

	def destroy
    @task.destroy
    redirect_to client_projects_path
  end

  protected

  def task_params
  	params.require(:task).permit(:name, :billable)
  end

  def load_task
  	@task = @projects.tasks.find([:id])
  end

  def load_project
    @project = Project.find(params[:project_id])
  end

  def load_client
  	@client = Client.find(params[:client_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/clients/_clients.html.erb
 <% @clients.each do |client| %>
  <h3><%= link_to client.name, client_path(client) %></h3>
<% end %> 

app/views/clients/_form.html.erb
<div class="form-group">
  <%= form.text_field :name, class: 'form-control', placeholder: 'Client Name' %>
</div>

app/views/clients/edit.html.erb
<div class='client-edit'>
	<%= form_for @client, role: 'form' do |form| %>
		<%= render form %>		
		<%= form.submit "Update", class: 'btn btn-primary' %>	
	<% end %>
</div>

app/views/clients/index.html.erb
</br>

<%= link_to "Add Client", new_client_path %>

<div class='client-list'>
	<h2>Client List</h2>

	<%= render 'clients' %>
</div>

app/views/clients/new.html.erb
<div class='client-add'>
	<%= form_for @client, role: 'form' do |form| %>
		<%= render form %>		
		<%= form.submit "Add Client", class: 'btn btn-primary' %>	
	<% end %>
</div>

app/views/clients/show.html.erb
<%= link_to "Back to client list", clients_path %><br/>

<h2><%= @client.name %></h2>

<%= link_to "Edit", [:edit, @client] %>
<%= link_to "delete client", @client, method: :delete, confirm: "Confirm delete?" %>


<h3>Projects:</h3>
<p><%= link_to "Add a project", new_client_project_path(@client) %></p>

<% @client.projects.each do |project| %>
  <h4><%= link_to project.name, [@client, project] %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>HarvestClone</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class='container'>
			<div class="user_nav">  
			  <% if current_user %>  
			    Logged in as <%= current_user.email %>.  
			    <%= link_to "Log out", logout_path %> 
			  <% else %>   
			    <%= link_to "Log in", login_path  %> 
			  <% end %>  
			</div>  
			<% flash.each do |name, msg| %>  
			  <%= content_tag :div, msg, :id => "flash_#{name}" %>  
			<% end %>  
			<%= yield %>
		</div>
	</body>
</html>

app/views/projects/_form.html.erb
<div class="form-group">
	<%= form.text_field :name, class: 'form-control', placeholder: 'Project Name' %>
</div>

app/views/projects/new.html.erb
</br>
<div class='project-add'>
	<%= form_for [@client, @project], role: 'form' do |form| %>
		<%= render form %>
	  <%= form.submit "Add Project", class: 'btn btn-primary' %>	  		
	<% end %>
</div>

app/views/projects/show.html.erb
<%= link_to "Back to #{@client.name} tasks", client_path(@client) %><br/>

<h2><%= @project.name %></h2>

<%= link_to "delete project", [@client, @project], method: :delete, confirm: "Confirm delete?" %>


<h3>Tasks:</h3>
<p><%= link_to "Add a task", new_client_project_task_path(project_id: @project.id) %></p>

<% @project.tasks.each do |task| %>
  <h4><%= link_to task.name, [@project, task] %></h4>
<% end %>

app/views/tasks/_form.html.erb
<div class="form-group">
  <%= form.text_field :name, class: 'form-control', placeholder: 'Task Name' %>
</div>

<div class="checkbox">
	<%= form.checkbox :billable, type="checkbox"  %> Billable?
</div>

app/views/tasks/new.html.erb
</br>
<div class='task-add'>
	<%= form_for [@client, @project, @task], role: 'form' do |form| %>

		<%= render form %>

	  <%= form.submit "Add Task", class: 'btn btn-primary' %>	  		
	<% end %>
</div>